Fix disk build with <bootloader name="custom"/>
* Fix DiskBuilder.create_disk() to not call the BootLoaderConfig
  factory when bootloader=custom. The factory does not recognize the
  "custom" bootloader name and raises the following exception:
  KiwiBootLoaderConfigSetupError: Support for custom bootloader config not implemented
* Update DiskBuilder._install_bootloader() to not invoke any
  bootloader_config methods when bootloader=custom since no config
  instance is created in such a case.